AllCops:
  Exclude:
    - config/**/*
    - Capfile
    - tasks/*
    - config.ru
    - Gemfile
    - spec/*
    - lib/**/**/*

Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 150
  Enabled: false

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 100
  Enabled: false

Naming/FileName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/AbcSize:
  Max: 60

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 80

Metrics/PerceivedComplexity:
  Max: 60
